# Use the official Node.js 22 image as the base image
FROM node:22

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate Prisma
RUN npx prisma generate

EXPOSE 3000

#CMD ["tail", "-f", "/dev/null"]
CMD ["npm", "run", "dev"]

