CREATE TABLE `users` (
  `id_user` int(11) NOT NULL AUTO_INCREMENT,
  `fid_media` int(11) DEFAULT NULL,
  `user_status` char(2) DEFAULT 'PC',
  `user_level` tinyint(4) DEFAULT 0,
  `user_username` varchar(64) NOT NULL,
  `user_gender` varchar(4) DEFAULT 'M',
  `user_dob` datetime DEFAULT NULL,
  `user_city` varchar(64) DEFAULT NULL,
  `user_state` varchar(64) DEFAULT NULL,
  `user_postal` varchar(64) DEFAULT NULL,
  `user_country` varchar(3) DEFAULT NULL,
  `user_latitude` decimal(10,8) DEFAULT 0.00000000,
  `user_longitude` decimal(10,8) DEFAULT 0.00000000,
  `user_joined` datetime DEFAULT CURRENT_TIMESTAMP,
  `user_login` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_bio` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE KEY `user_username_UNIQUE` (`user_username`),
  KEY `fid_media` (`fid_media`),
  KEY `user_status` (`user_status`),
  KEY `user_level` (`user_level`),
  KEY `user_username` (`user_username`),
  KEY `user_gender` (`user_gender`),
  KEY `user_dob` (`user_dob`),
  KEY `user_city` (`user_city`),
  KEY `user_state` (`user_state`),
  KEY `user_postal` (`user_postal`),
  KEY `user_country` (`user_country`),
  KEY `user_latitude` (`user_latitude`),
  KEY `user_longitude` (`user_longitude`),
  KEY `user_joined` (`user_joined`),
  KEY `user_joined_desc` (`user_joined` DESC),
  KEY `user_login` (`user_login`),
  KEY `user_login_desc` (`user_login` DESC),
  CONSTRAINT `fk_user_media` FOREIGN KEY (`fid_media`) REFERENCES `media` (`id_media`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
